version: "3.8"

services:
  app:
    build: .
    container_name: magazine_generator
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/magazine_db
    command: uvicorn app:main --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  db:
    image: ankane/pgvector:latest  # PostgreSQL with pgvector
    container_name: magazine_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: magazine_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: