[project]
name = "magazine-api-hybrid-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.1.3",
    "faker>=35.2.0",
    "pandas>=2.2.3",
    "ruff>=0.9.4",
    "sentence-transformers>=3.4.1",
]
